### PR TITLE
add transfer benchmarks

### PR DESCRIPTION
**Pull request by waitfreemaxi**

### CODE REVIEW

**Comment by waitfreemaxi** [comment]
```
transfers/transfer_checked
                        time:   [1.3442 µs 1.3505 µs 1.3569 µs]
                        thrpt:  [736.96 Kelem/s 740.45 Kelem/s 743.92 Kelem/s]
                 change:
                        time:   [-20.833% -20.260% -19.761%] (p = 0.00 < 0.05)
                        thrpt:  [+24.628% +25.407% +26.316%]
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) low mild
transfers/transfer_unchecked
                        time:   [1.3002 µs 1.3097 µs 1.3194 µs]
                        thrpt:  [757.93 Kelem/s 763.51 Kelem/s 769.09 Kelem/s]
                 change:
                        time:   [-21.279% -20.506% -19.807%] (p = 0.00 < 0.05)
                        thrpt:  [+24.698% +25.796% +27.031%]
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) low mild
  1 (1.00%) high severe
```

**Comment by buffalojoec** [comment]
Looks like about 20% faster?

**Comment by waitfreemaxi** [comment]
Yes. The point is not to compare to ProgramTest.

Sigverify caps out at 30k per second per core, even with fd_ed25519.

**Review by buffalojoec — APPROVED** [review]
Lgtm, thanks for adding this! I'll probably use what you've laid down here to build other benches as the API matures.

**Comment by waitfreemaxi** [comment]
🫡

**Pull request merged**
